export const columns = {
  training_type: {
    index: 1,
    name: "Training Type",
    value: "training_type",
    width: 8,
    isMandatory: true,
  },
  training_topic_name: {
    index: 2,
    name: "Training Topic",
    value: "training_topic_name",
    width: 10,
    isMandatory: true,
  },
  training_test_name: {
    index: 3,
    name: "Training Test Name",
    value: "training_test_name",
    width: 12,
    isMandatory: true,
  },
  evaluation: {
    index: 4,
    name: "Evaluation",
    value: "evaluation",
    width: 7,
    isMandatory: true,
  },
  control_no: {
    index: 5,
    name: "Control No.",
    value: "control_no",
    width: 7,
  },
  revision: {
    index: 6,
    name: "Revision No.",
    value: "revision",
    width: 7,
  },
  pre_test_result: {
    index: 7,
    name: "Pre-Test Result",
    value: "pre_test_result",
    width: 8,
    isMandatory: true,
  },
  post_test_result: {
    index: 8,
    name: "Post-Test Result",
    value: "post_test_result",
    width: 9,
    isMandatory: true,
  },
  post_attempts: {
    index: 9,
    name: "No. of Attempts",
    value: "post_attempts",
    width: 8,
    isMandatory: true,
  },
  training_time: {
    index: 10,
    name: "Training Date & Time",
    value: "training_time",
    width: 10,
  },
  staff_id: {
    index: 11,
    name: "Staff ID",
    value: "staff_id",
    width: 7,
    isMandatory: true,
  },
  staff_name: {
    index: 12,
    name: "Name",
    value: "staff_name",
    width: 10,
    isMandatory: true,
  },
  staff_level: {
    index: 13,
    name: "Level",
    value: "staff_level",
    width: 7,
  },
  trainer_id: {
    index: 14,
    name: "Trainer Staff ID",
    value: "trainer_id",
    width: 9,
  },
  trainer_name: {
    index: 15,
    name: "Trainer Name",
    value: "trainer_name",
    width: 10,
  },
  station: {
    index: 16,
    name: "Station",
    value: "station",
    width: 7,
  },
  area: {
    index: 17,
    name: "Area",
    value: "area",
    width: 7,
  },
  line: {
    index: 18,
    name: "Line",
    value: "line",
    width: 7,
  },
  group: {
    index: 19,
    name: "Group",
    value: "group",
    width: 7,
  },
  shop: {
    index: 20,
    name: "Shop",
    value: "shop",
    width: 7,
  },
  plant: {
    index: 21,
    name: "Plant",
    value: "plant",
    width: 7,
  },
};

export const columnsSupervisor = {
  view_details: {
    index: 1,
    name: "",
    value: "view_details",
    width: 5,
    isMandatory: true,
    isHideSorting: true,
  },
  staff_id: {
    index: 2,
    name: "Staff ID",
    value: "staff_id",
    width: 6,
    isMandatory: true,
  },
  staff_name: {
    index: 3,
    name: "Name",
    value: "staff_name",
    width: 8,
    isMandatory: true,
  },
  station_name: {
    index: 4,
    name: "Process Station",
    value: "station_name",
    width: 10,
    isMandatory: true,
  },
  station_type: {
    index: 5,
    name: "Station Type",
    value: "station_type",
    width: 8,
  },
  ojt_type: {
    index: 6,
    name: "Type of OJT",
    value: "ojt_type",
    width: 8,
    isMandatory: true,
  },
  training_start_date: {
    index: 7,
    name: "Training State Date",
    value: "training_start_date",
    width: 8,
  },
  training_end_date: {
    index: 8,
    name: "Training End Date",
    value: "training_end_date",
    width: 8,
  },
  training_duration: {
    index: 9,
    name: "Training Duration (days)",
    value: "training_duration",
    width: 8,
  },
  plant_name: {
    index: 10,
    name: "Plant",
    value: "plant_name",
    width: 8,
  },
  shop_name: {
    index: 11,
    name: "Shop",
    value: "shop_name",
    width: 8,
  },
  group_name: {
    index: 12,
    name: "Group",
    value: "group_name",
    width: 8,
  },
  line_name: {
    index: 13,
    name: "Line",
    value: "line_name",
    width: 8,
  },
  area_name: {
    index: 14,
    name: "Area",
    value: "area_name",
    width: 8,
    isMandatory: true,
  },
};
