export const SMM_ALLOCATION_STAFF_DETAIL_LOADING =
  "SMM_ALLOCATION_STAFF_DETAIL_LOADING";
export const SMM_ALLOCATION_STAFF_DETAIL_DATA =
  "SMM_ALLOCATION_STAFF_DETAIL_DATA";

export const SMM_ALLOCATION_AREA_DETAIL_LOADING =
  "SMM_ALLOCATION_AREA_DETAIL_LOADING";
export const SMM_ALLOCATION_AREA_DETAIL_DATA =
  "SMM_ALLOCATION_AREA_DETAIL_DATA";

export const SMM_STAFF_AREA_ALLOCATION_LOADING =
  "SMM_STAFF_AREA_ALLOCATION_LOADING";
export const SMM_STAFF_AREA_ALLOCATION_DATA = "SMM_STAFF_AREA_ALLOCATION_DATA";
