//ongoing batch api
export const SMM_SET_REFRESHER_ONGOING_BATCH_LOADING =
  "SMM_SET_REFRESHER_ONGOING_BATCH_LOADING";
export const SMM_SET_REFRESHER_ONGOING_BATCH_DATA =
  "SMM_SET_REFRESHER_ONGOING_BATCH_DATA";
//training plan api
export const SMM_SET_REFRESHER_TRAINING_PLAN_LOADING =
  "SMM_SET_REFRESHER_TRAINING_PLAN_LOADING";
export const SMM_SET_REFRESHER_TRAINING_PLAN =
  "SMM_SET_REFRESHER_TRAINING_PLAN";
//Attendee Details
export const SMM_SET_REFRESHER_ATTENDEE_DETAILS_LOADING =
  "SMM_SET_REFRESHER_ATTENDEE_DETAILS_LOADING";
export const SMM_SET_REFRESHER_ATTENDEE_DETAILS =
  "SMM_SET_REFRESHER_ATTENDEE_DETAILS";
export const SMM_SET_REFRESHER_ATTENDEE_BATCH_DETAILS_LOADING =
  "SMM_SET_REFRESHER_ATTENDEE_BATCH_DETAILS_LOADING";
export const SMM_SET_REFRESHER_ATTENDEE_BATCH_DETAILS =
  "SMM_SET_REFRESHER_ATTENDEE_BATCH_DETAILS";
export const SMM_SET_REFRESHER_ATTENDEE_STAFF_LIST =
  "SMM_SET_REFRESHER_ATTENDEE_STAFF_LIST";
export const SMM_SET_REFRESHER_ATTENDEE_STAFF_LIST_LOADING =
  "SMM_SET_REFRESHER_ATTENDEE_STAFF_LIST_LOADING";
//New Refersher Training
export const SMM_SET_REFRESHER_TRAINING_TOPICS =
  "SMM_SET_REFRESHER_TRAINING_TOPICS";
export const SMM_SET_REFRESHER_TRAINING_TOPICS_LOADING =
  "SMM_SET_REFRESHER_TRAINING_TOPICS_LOADING";
//Save Selected
export const SMM_SET_CLASSROOM_TRAINING_CREATE_BATCH_STATUS =
  "SMM_SET_CLASSROOM_TRAINING_CREATE_BATCH_STATUS";
export const SMM_SET_CLASSROOM_TRAINING_CREATED_BATCH_ID =
  "SMM_SET_CLASSROOM_TRAINING_CREATED_BATCH_ID";
//Attendees Training Record
export const SMM_CLASSROOM_TRAINING_ATTENDEES_RECORD_LOADING =
  "SMM_CLASSROOM_TRAINING_ATTENDEES_RECORD_LOADING";
export const SMM_CLASSROOM_TRAINING_ATTENDEES_RECORD_DATA =
  "SMM_CLASSROOM_TRAINING_ATTENDEES_RECORD_DATA";
//Mark Attendance
export const SMM_CLASSROOM_TRAINING_MARK_ATTENDANCE_LOADING =
  "SMM_CLASSROOM_TRAINING_MARK_ATTENDANCE_LOADING";
export const SMM_CLASSROOM_TRAINING_MARK_ATTENDANCE_STATUS =
  "SMM_CLASSROOM_TRAINING_MARK_ATTENDANCE_STATUS";
export const SMM_UPDATE_CLASSROOM_TAB_SELECTION =
  "SMM_UPDATE_CLASSROOM_TAB_SELECTION";
//Update Batch
export const SMM_CLASSROOM_TRAINING_UPDATE_BATCH_LOADING =
  "SMM_CLASSROOM_TRAINING_UPDATE_BATCH_LOADING";
export const SMM_CLASSROOM_TRAINING_UPDATE_BATCH_DATA =
  "SMM_CLASSROOM_TRAINING_UPDATE_BATCH_DATA";
//Batch Topics
export const SMM_CLASSROOM_TRAINING_BATCH_TOPICS_LOADING =
  "SMM_CLASSROOM_TRAINING_BATCH_TOPICS_LOADING";
export const SMM_CLASSROOM_TRAINING_BATCH_TOPICS_DATA =
  "SMM_CLASSROOM_TRAINING_BATCH_TOPICS_DATA";
//Update Topics Status
export const SMM_CLASSROOM_TRAINING_UPDATE_TOPICS_STATUS_LOADING =
  "SMM_CLASSROOM_TRAINING_UPDATE_TOPICS_STATUS_LOADING";
export const SMM_CLASSROOM_TRAINING_UPDATE_TOPICS_STATUS_DATA =
  "SMM_CLASSROOM_TRAINING_UPDATE_TOPICS_STATUS_DATA";
//Reattempt Status
export const SMM_CLASSROOM_TRAINING_REATTEMPT_STATUS_LOADING =
  "SMM_CLASSROOM_TRAINING_REATTEMPT_STATUS_LOADING";
export const SMM_CLASSROOM_TRAINING_REATTEMPT_STATUS_DATA =
  "SMM_CLASSROOM_TRAINING_REATTEMPT_STATUS_DATA";
//Fetch Staff
export const SMM_CLASSROOM_TRAINING_FETCH_STAFF_SEARCH_LOADING =
  "SMM_CLASSROOM_TRAINING_FETCH_STAFF_SEARCH_LOADING";
export const SMM_CLASSROOM_TRAINING_FETCH_STAFF_SEARCH_DATA =
  "SMM_CLASSROOM_TRAINING_FETCH_STAFF_SEARCH_DATA";
//Save Topic Completed
export const SMM_CLASSROOM_TRAINING_SAVE_TOPIC_COMPLETED_LOADING =
  "SMM_CLASSROOM_TRAINING_SAVE_TOPIC_COMPLETED_LOADING";
export const SMM_CLASSROOM_TRAINING_SAVE_TOPIC_COMPLETED_DATA =
  "SMM_CLASSROOM_TRAINING_SAVE_TOPIC_COMPLETED_DATA";
//Test Attempt View
export const SMM_CLASSROOM_TRAINING_TEST_VIEW_LOADING =
  "SMM_CLASSROOM_TRAINING_TEST_VIEW_LOADING";
export const SMM_CLASSROOM_TRAINING_TEST_VIEW_DATA =
  "SMM_CLASSROOM_TRAINING_TEST_VIEW_DATA";
//Delete Batch
export const SMM_CLASSROOM_TRAINING_DELETE_BATCH =
  "SMM_CLASSROOM_TRAINING_DELETE_BATCH";
export const SMM_CLASSROOM_TRAINING_DELETE_BATCH_LOADING =
  "SMM_CLASSROOM_TRAINING_DELETE_BATCH-LOADING";
//Submit Trinaer Evaluation
export const SMM_CLASSROOM_TRAINING_SUBMIT_TRAINER_EVALUATION =
  "SMM_CLASSROOM_TRAINING_SUBMIT_TRAINER_EVALUATION";
export const SMM_CLASSROOM_TRAINING_SUBMIT_TRAINER_EVALUATION_LOADING =
  "SMM_CLASSROOM_TRAINING_SUBMIT_TRAINER_EVALUATION_LOADING";
//Fetch Trainer Question Paper
export const SMM_CLASSROOM_TRAINING_TRAINER_TEST_QUESTION_DATA =
  "SMM_CLASSROOM_TRAINING_TRAINER_TEST_QUESTION_DATA";
export const SMM_CLASSROOM_TRAINING_TRAINER_TEST_QUESTION_DATA_LOADING =
  "SMM_CLASSROOM_TRAINING_TRAINER_TEST_QUESTION_DATA_LOADING";
//SUBMIT Test Paper
export const SMM_CLASSROOM_TRAINING_SUBMIT_TEST_DATA =
  "SMM_CLASSROOM_TRAINING_SUBMIT_TEST_DATA";
export const SMM_CLASSROOM_TRAINING_SUBMIT_TEST_DATA_LOADING =
  "SMM_CLASSROOM_TRAINING_SUBMIT_TEST_DATA_LOADING";
//Pending Batch
export const SMM_CLASSROOM_TRAINING_PENDING_BATCH_LOADING =
  "SMM_CLASSROOM_TRAINING_PENDING_BATCH_LOADING";
export const SMM_CLASSROOM_TRAINING_PENDING_BATCH_DATA =
  "SMM_CLASSROOM_TRAINING_PENDING_BATCH_DATA";
