//new joinee and existing table data
export const SMM_SET_STAFF_TRAINING_DETAILS_DATA =
  "SMM_SET_STAFF_TRAINING_DETAILS_DATA";
export const SMM_SET_STAFF_TRAINING_DETAILS_DATA_LOADING =
  "SMM_SET_STAFF_TRAINING_DETAILS_DATA_LOADING";
//fetch all area stations
export const SMM_SET_AREA_STATIONS_DATA = "SMM_SET_AREA_STATIONS_DATA";
export const SMM_SET_AREA_STATIONS_DATA_LOADING =
  "SMM_SET_AREA_STATIONS_DATA_LOADING";
//Save OJT test data
export const SMM_SAVE_OJT_TEST_DATA = "SMM_SAVE_OJT_TEST_DATA";
export const SMM_SAVE_OJT_TEST_DATA_LOADING = "SMM_SAVE_OJT_TEST_DATA_LOADING";
//fetch ojt test data
export const SMM_FETCH_OJT_TEST_DATA = "SMM_FETCH_OJT_TEST_DATA";
export const SMM_FETCH_OJT_TEST_DATA_LOADING =
  "SMM_FETCH_OJT_TEST_DATA_LOADING";
 //update station and start training
 export const SMM_SET_SAVE_STATION_DATA = 
 "SMM_SET_SAVE_STATION_DATA";
 export const SMM_SET_SAVE_STATION_DATA_LOADING = 
 "SMM_SET_SAVE_STATION_DATA_LOADING";
 //reset and delete training
 export const SMM_OJT_DELETE_TRAINING = "SMM_OJT_DELETE_TRAINING";
 export const SMM_OJT_DELETE_TRAINING_LOADING = "SMM_OJT_DELETE_TRAINING_LOADING";
 //navigate next training level
 export const SMM_NAVIGATE_NEXT_TRAINING="SMM_NAVIGATE_NEXT_TRAINING";
 export const SMM_NAVIGATE_NEXT_TRAINING_LOADING="SMM_NAVIGATE_NEXT_TRAINING_LOADING";
 //upload jpeg/pdf for maru A/AR
 export const SMM_UPLOAD_PDF_IMAGE_STATUS="SMM_UPLOAD_PDF_IMAGE_STATUS";
 export const SMM_UPLOAD_PDF_IMAGE_STATUS_DATA="SMM_UPLOAD_PDF_IMAGE_STATUS_DATA";
//  //download jpeg/pdf for Maru A/AR
//  export const SMM_DOWNLOAD_PDF_IMAGE_STATUS="SMM_DOWNLOAD_PDF_IMAGE_STATUS";
//  export const SMM_DOWNLOAD_PDF_IMAGE_STATUS_DATA="SMM_DOWNLOAD_PDF_IMAGE_STATUS_DATA";
 //fetch existing operators
 export const SMM_SET_EXISTING_OPERATORS_DATA = "SMM_SET_EXISTING_OPERATORS_DATA";
 export const SMM_SET_EXISTING_OPERATORS_DATA_LOADING =
   "SMM_SET_EXISTING_OPERATORS_DATA_LOADING";
//Complete Training
export const SMM_SET_COMPLETE_TRAINING_DATA = "SMM_SET_COMPLETE_TRAINING_DATA";
export const SMM_SET_COMPLETE_TRAINING_DATA_LOADING =
  "SMM_SET_COMPLETE_TRAINING_DATA_LOADING";