export const SMM_SET_MASTER_FILES = "SMM_SET_MASTER_FILES";
export const SMM_ADD_MASTER_FILE = "SMM_ADD_MASTER_FILE";
export const SMM_SET_MASTER_LOADING = "SMM_SET_MASTER_LOADING";
export const SMM_SET_UPLOAD_MASTER_LOADING = "SMM_SET_UPLOAD_MASTER_LOADING";
export const SMM_SET_APPROVED = "SMM_SET_APPROVED";

export const SMM_ADD_MASTER_FILE_API_STATUS = "SMM_ADD_MASTER_FILE_API_STATUS";
