export const SMM_SET_REPORT_FILTER_LOADING = "SMM_SET_REPORT_FILTER_LOADING";
export const SMM_SET_REPORT_FILTER_DATA = "SMM_SET_REPORT_FILTER_DATA";
export const SMM_SET_STAFF_SEARCH_LOADING = "SMM_SET_STAFF_SEARCH_LOADING";
export const SMM_SET_STAFF_SEARCH_DATA = "SMM_SET_STAFF_SEARCH_DATA";
export const SMM_SET_STAFF_DETAILS_LOADING = "SMM_SET_STAFF_DETAILS_LOADING";
export const SMM_SET_STAFF_DETAILS_DATA = "SMM_SET_STAFF_DETAILS_DATA";
export const SMM_SET_REPORT_COLUMN = "SMM_SET_REPORT_COLUMN";
export const SMM_SET_COMBINED_REPORT_DATA = "SMM_SET_COMBINED_REPORT_DATA";
export const SMM_SET_SUPERVISOR_STAFF_STATION_LOADING =
  "SMM_SET_SUPERVISOR_STAFF_STATION_LOADING";
export const SMM_SET_SUPERVISOR_STAFF_STATION_DATA =
  "SMM_SET_SUPERVISOR_STAFF_STATION_DATA";
export const SMM_SET_SUPERVISOR_REPORT_COLUMN =
  "SMM_SET_SUPERVISOR_REPORT_COLUMN";
export const SMM_SET_SUPERVISOR_STAFF_REPORTS_LOADING =
  "SMM_SET_SUPERVISOR_STAFF_REPORTS_LOADING";
export const SMM_SET_SUPERVISOR_STAFF_REPORTS_DATA =
  "SMM_SET_SUPERVISOR_STAFF_REPORTS_DATA";
export const SMM_SET_DPM_PLANT_AREA_DETAIL_LOADING =
  "SMM_SET_DPM_PLANT_AREA_DETAIL_LOADING";
export const SMM_SET_DPM_PLANT_AREA_DETAIL_DATA =
  "SMM_SET_DPM_PLANT_AREA_DETAIL_DATA";
