export const SMM_SET_SITES = "SMM_SET_SITES";
export const SMM_SET_SHOP = "SMM_SET_SHOP";
export const SMM_SET_SITE = "SMM_SET_SITE";
export const SMM_SET_LOCATION = "SMM_SET_LOCATION";
export const SMM_SET_PLANT = "SMM_SET_PLANT";
export const SMM_SET_LOADING = "SMM_SET_LOADING";
export const SMM_FILTERS_CHANGED = "SMM_FILTERS_CHANGED";
//
export const SMM_SET_SUBCATEGORY="SMM_SET_SUBCATEGORY";
export const SMM_SET_GROUP="SMM_SET_GROUP";
export const SMM_SET_LINE="SMM_SET_LINE";
export const SMM_SET_AREA="SMM_SET_AREA";
